### ISSUE TITLE
LANG_PROJECT_ID.tooling missing Gson dependency

### ISSUE THREAD

**Issue by fralalonde** [bruno-medeiros/MelnormeEclipse#9]
Hi, I've followed the Eclipse setup instruction _to the letter_ but I'm still missing the Gson dependency for module LANG_PROJECT_ID.tooling. This results in classes melnorme.lang.utils.gson.GsonHelper and melnorme.lang.utils.gson.JsonParserX not compiling. Other than that, the project and modules loads successfully in Eclipse.

The only libs that show up in the generated target platform repository are JUnit (4.12) and Hamcrest (1.3.0). Should those even be there? From the command line, Maven successfully completes building both the root project and the target-platform project. 

I'm using Neon.1 on Windows 10 x64 (if that changes anything)

I've searched around the poms, both immediate and in maven-jar. It is still not clear to me how the dependencies are declared and migrate from one layer to the other - I've tried changing the pom-declared Gson version to 2.7, but I still see 2.2.4 being referenced in the Maven debug trace.

**Comment by bruno-medeiros** [comment]
Yeah, there was a recent change that broke the development setup. The Maven poms only affect the build, they don't affect the development setup (unfortunately due to a limitation in the tools, these two things are setup separately, and sometimes they can get out of sync)

**Comment by fralalonde** [comment]
Ok! I'll resync later until it is fixed.

Thanks.
